import type { Metadata } from "next";
import { Inter, Lora, Poppins } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const localization = {
    signUp: {
      start: {
        subtitle:
          "Sign up to rate and review your favorite HealthyFulRecipes recipes.",
      },
    },
    signIn: {
      start: {
        subtitle:
          "Welcome back! Please sign in to rate and review your favorite HealthyFulRecipes recipes.",
      },
    },
  };
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body
          className={clsx(
            poppins.variable,
            lora.variable,
            "h-full w-full bg-white font-sans antialiased"
          )}
        >
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
